# Generated by Django 4.2.1 on 2024-06-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0008_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
