# Generated by Django 5.0.6 on 2024-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
