# Generated by Django 4.2.1 on 2024-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0011_alter_payment_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
