# Generated by Django 4.2.1 on 2024-06-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0012_loans_approval_date'),
        ('loans_borrower', '0013_payment'),
    ]

    operations = [
    ]
