# Generated by Django 4.2.1 on 2024-06-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0015_remove_loans_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_tag',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Delinquent', 'Delinquent'), ('In-Loan Default', 'In-Loan Default'), ('Completed', 'Completed')], default='Pending', max_length=100, null=True),
        ),
    ]
