# Generated by Django 5.0.6 on 2024-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_manage_acc', '0002_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='deposit_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
