# Generated by Django 4.2.1 on 2024-06-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_manage_acc', '0004_bankaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
