@echo off
python -m venv .venv
call .venv/Scripts/activate.bat
pip install agora-token-builder
pip install anyio
pip install appdirs
pip install arabic-reshaper
pip install argon2-cffi
pip install argon2-cffi-bindings
pip install asgiref
pip install asn1crypto
pip install asttokens
pip install attrs
pip install autopep8
pip install Babel
pip install backcall
pip install beautifulsoup4
pip install bleach
pip install bs4
pip install certifi
pip install cffi
pip install charset-normalizer
pip install click
pip install click-plugins
pip install cligj
pip install colorama
pip install crispy-bootstrap5
pip install cryptography
pip install cssselect2
pip install cycler
pip install debugpy
pip install decorator
pip install defusedxml
pip install Django
pip install django-crispy-forms
pip install django-easy-pdf
pip install django-filter
pip install django-money
pip install django-phonenumber-field
pip install entrypoints
pip install et-xmlfile
pip install executing
pip install fastjsonschema
pip install flake8
pip install fonttools
pip install future
pip install gunicorn
pip install html5lib
pip install humanize
pip install idna
pip install igraph
pip install ipykernel
pip install ipython
pip install ipython-genutils
pip install jedi
pip install Jinja2
pip install joblib
pip install json5
pip install jsonschema
pip install jupyter-client
pip install jupyter-core
pip install jupyter-server
pip install jupyterlab
pip install jupyterlab-pygments
pip install jupyterlab-server
pip install kiwisolver
pip install lxml
pip install MarkupSafe
pip install matplotlib
pip install matplotlib-inline
pip install mccabe
pip install mistune
pip install munch
pip install mysqlclient
pip install nbclassic
pip install nbclient
pip install nbconvert
pip install nbformat
pip install nest-asyncio
pip install networkx
pip install notebook
pip install notebook-shim
pip install numpy
pip install numpy-financial
pip install openpyxl
pip install oscrypto
pip install packaging
pip install pandas
pip install pandocfilters
pip install parso
pip install permutation
pip install phonenumbers
pip install pickleshare
pip install Pillow
pip install prometheus-client
pip install prompt-toolkit
pip install psutil
pip install pure-eval
pip install py-moneyed
pip install pycodestyle
pip install pycparser
pip install pyflakes
pip install Pygments
pip install pyHanko
pip install pyhanko-certvalidator
pip install pyparsing
pip install PyPDF3
pip install pyproj
pip install pyrsistent
pip install python-bidi
pip install python-dateutil
pip install python-igraph
pip install python-louvain
pip install pytz
pip install pytz-deprecation-shim
pip install PyYAML
pip install pyzmq
pip install qrcode
pip install reportlab
pip install requests
pip install scikit-learn
pip install scipy
pip install seaborn
pip install Send2Trash
pip install Shapely
pip install six
pip install sniffio
pip install soupsieve
pip install sqlparse
pip install stack-data
pip install svglib
pip install terminado
pip install texttable
pip install threadpoolctl
pip install thresholdclustering
pip install tinycss2
pip install toml
pip install tornado
pip install tqdm
pip install traitlets
pip install tzdata
pip install tzlocal
pip install uritools
pip install urllib3
pip install wcwidth
pip install webencodings
pip install websocket-client
pip install whitenoise
pip install xhtml2pdf