# Generated by Django 4.2.1 on 2024-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_officer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
