# Generated by Django 4.2.1 on 2024-06-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_officer', '0002_alter_deposit_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
